# action.yml
name: "Deploy workspace folder to repo"
description: "Push files generated during the workflow run to an external repository"
author: "jigglycrumb"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "upload-cloud"
  color: "black"
